default: &default
  application_name: LIMS
  dde_server: 127.0.0.1:3009
  dde_username: admin5
  dde_password: admin5
  site_code: KCH
  secure_connection: false

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
